Added complete datafiles to check if that causes the error
  File "/home/coco_langens/DeepLearningProject/network/evaluation.py", line 274, in <listcomp>
    for label_ix in range(level_start[level_id], level_stop[level_id])],
IndexError: index 1 is out of bounds for axis 0 with size 1